"""first migration

Revision ID: 44278545719c
Revises: 
Create Date: 2023-05-11 19:35:25.796311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44278545719c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.String(), nullable=False),
    sa.Column('regions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('courier_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('regions', sa.Integer(), nullable=False),
    sa.Column('delivery_hours', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('completed_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###
